enum actionTypes {
  SET_AUTHORIZED = 'SET_AUTHORIZED',
  SET_LOADER = 'SET_LOADER',
  SIGNIN = 'SIGNIN',
  SIGNOUT = 'SIGNOUT',
  SET_STEPS_FINISHED = 'SET_STEPS_FINISHED',
  CHECK_AUTHORIZATION_STATUS = 'CHECK_AUTHORIZATION_STATUS',
  SET_SIGNIN_ERROR_MSG = 'SET_SIGNIN_ERROR_MSG'
}

export default actionTypes;